@baseURL = http://localhost:8080/api/todo


################################

POST {{baseURL}}/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM2YTc1NGYzZmYzOGMyYzIzYzI0ZGUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjQ3NzQ5OTEwfQ.nyRVmXNfjh8Jwj3RGOf4l_Wncggz2MHKZ6Gc9iqeqCI

{
    "groupId":"623745443dda494d6d7d4151",
    "noteId":"623745e53dda494d6d7d4163",
    "todoName":"hien thi ai la admin"
}